hr_management/urls.py
from django.urls import path
from .views import EmployeeListView, EmployeeCreateView, EmployeeUpdateView, EmployeeDeleteView

urlpatterns = [
    path('', EmployeeListView.as_view(), name='employee_list'),
    path('add/', EmployeeCreateView.as_view(), name='employee_add'),
    path('<int:pk>/', EmployeeUpdateView.as_view(), name='employee_edit'),
    path('<int:pk>/delete/', EmployeeDeleteView.as_view(), name='employee_delete'),
]

menu/urls.py
from django.urls import path
from .views import (
    IngredientListView, IngredientCreateView, IngredientUpdateView, IngredientDeleteView,
    CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView,
    MenuListView, MenuCreateView, MenuUpdateView, MenuDeleteView, DashboardView
)

urlpatterns = [
    # Ingredient URLs
    path('ingredients', IngredientListView.as_view(), name='ingredient_list'),
    path('ingredients/create', IngredientCreateView.as_view(), name='ingredient_create'),
    path('ingredients/<int:pk>/update', IngredientUpdateView.as_view(), name='ingredient_update'),
    path('ingredients/<int:pk>/delete', IngredientDeleteView.as_view(), name='ingredient_delete'),
    
    # Category URLs
    path('categories', CategoryListView.as_view(), name='category_list'),
    path('categories/create', CategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/update', CategoryUpdateView.as_view(), name='category_update'),
    path('categories/<int:pk>/delete', CategoryDeleteView.as_view(), name='category_delete'),
    
    # Menu URLs
    path('menus', MenuListView.as_view(), name='menu_list'),
    path('menus/create', MenuCreateView.as_view(), name='menu_create'),
    path('menus/update/<int:pk>/', MenuUpdateView.as_view(), name='menu_update'),
    path('menus/delete/<int:pk>/', MenuDeleteView.as_view(), name='menu_delete'),
    
    path('', DashboardView.as_view(), name='dashboard'),
]

panda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('dashboard/', include('menu.urls')),
     path('order/', include('order_management.urls')),
     path('employee/', include('hr_management.urls')),
    path('', include('frontend.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hr_management/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Contact(models.Model):
    msg_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=70, default="")
    phone = models.CharField(max_length=70, default="")
    desc = models.CharField(max_length=500, default="")
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) # Delete profile when user is deleted
    address = models.TextField(null=True, blank=True)
    contact = models.CharField(max_length=15, null=True, blank=True)
    image = models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile' #show how we want it to be displayed
    
class Employee(models.Model):
    full_name = models.CharField(max_length=500, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    contact = models.CharField(max_length=15, null=True, blank=True)
    image = models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')
    position_choices = [
        ('manager', 'Manager'),
        ('waiter', 'Waiter'),
        ('chef', 'Chef'),
        ('cleaner', 'Cleaner'),
    ]
    position = models.CharField(max_length=20, choices=position_choices)
    salary = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    join_date = models.DateField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.full_name

hr_management/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Employee


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['address', 'contact', 'image']
        

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

hr_management/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from .models import Profile

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserUpdateForm, ProfileUpdateForm

from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Employee
from .forms import EmployeeForm

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            
            # Create a new Profile object for the user
            profile = Profile(user=user)
            profile.save()
            
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'frontend/signup.html', {'form': form})

@login_required
def profile_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST,
                                          request.FILES,
                                          instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile has been updated!')
            return redirect('profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }
    return render(request, 'frontend/profile_update.html', context)

class EmployeeListView(ListView):
    model = Employee
    template_name = 'hr_management/employee_list.html'
    context_object_name = 'employees'

class EmployeeCreateView(CreateView):
    model = Employee
    form_class = EmployeeForm
    template_name = 'hr_management/employee_form.html'
    success_url = reverse_lazy('employee_list')

class EmployeeUpdateView(UpdateView):
    model = Employee
    form_class = EmployeeForm
    template_name = 'hr_management/employee_form.html'
    success_url = reverse_lazy('employee_list')

class EmployeeDeleteView(DeleteView):
    model = Employee
    template_name = 'hr_management/employee_confirm_delete.html'
    success_url = reverse_lazy('employee_list')

hr_management/templates/hr_management/employee_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="flex min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8 rounded-3xl bg-gray-100  ">
  <div class="w-full space-y-8 px-5">
    <div class="col-lg-10 col-md-8 offset-md-1" style="background: transparent !important; margin-left:15rem">
      <div class=" col-md-5 offset-md-1 ">
        <div class="detail-box" style="width:50%;">
          <div class="container mt-5">
            <h2>Delete Employee?</h2>
            <hr>
            <p  class="mb-5 mt-5">Are you sure you want to delete "{{ object }}"?</p>
            <form method="post" style="display: inline;">
              {% csrf_token %}
              <button type="submit" class="inline-flex justify-center rounded-md bg-red-600 py-2 px-5 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-500 w-full">Delete</button>
            </form>
            <a href="{% url 'employee_list' %}" class="inline-flex justify-center rounded-md bg-gray-600 py-2 px-5 text-sm font-semibold text-white shadow-sm hover:bg-gray-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-500 w-full mt-3">Cancel</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

hr_management/templates/hr_management/employee_form.html
{% extends 'base.html' %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.3.js"></script>

{% block content %}
<div class="flex min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8 rounded-3xl bg-gray-100  ">
  <div class="w-full space-y-8 px-5">
      <div class="col-lg-10 col-md-8 offset-md-1" style="background: transparent !important; margin-left:15rem">
        <div class=" col-md-5 offset-md-1 ">
          <div class="detail-box">
            <div class="container ">
              <h2 class="pb-3">{% if form.instance.pk %}Update{% else %}Add{% endif %} Employee</h2>
              <hr>
              <form method="post" enctype="multipart/form-data" id="emp-form" style="width:60%;" class="pt-4">
        {% csrf_token %}
{{ form.as_p }}
        {% comment %} {% if form.errors %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <strong class="font-bold">Oops! Something went wrong.</strong>
                <span class="block sm:inline">{{ form.errors }}</span>
            </div>
        {% endif %}
        {% for field in form %}
            <div class="-space-y-px rounded-md shadow-sm">
                {{ field.errors }}
                {% if field.name == "full_name" %}
                    <label class="block text-sm font-medium leading-6 text-gray-800 pb-2 pt-3">Full Name</label>
                    <input type="{{ field.field.widget.input_type }}"
                    name="{{ field.name }}"
                    {% if field.value %}value="{{ field.value }}"{% endif %}
                    class="px-4 relative block w-full rounded-t-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                    placeholder="{{ field.label }}">
                {% elif field.name == "address" %}
                    <label class="block text-sm font-medium leading-6 text-gray-800 pb-2 pt-3">Address</label>
                    <textarea type="{{ field.field.widget.input_type }}"
                    name="{{ field.label }}"
                    {% if field.value %}value="{{ field.value }}"{% endif %}
                    class="px-4 relative block w-full rounded-t-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                    placeholder="{{ field.label }}"></textarea>
                {% elif field.name == "contact" %}
                    <label class="block text-sm font-medium leading-6 text-gray-800 pb-2 pt-3">Contact Number</label>
                    <input type="{{ field.field.widget.input_type }}"
                    name="{{ field.label }}"
                    {% if field.value %}value="{{ field.value }}"{% endif %}
                    class="px-4 relative block w-full rounded-t-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                    placeholder="{{ field.label }}">
                {% elif field.name == "salary" %}
                    <label class="block text-sm font-medium leading-6 text-gray-800 pb-2 pt-3">Salary</label>
                    <input type="{{ field.field.widget.input_type }}"
                    name="{{ field.label }}"
                    {% if field.value %}value="{{ field.value }}"{% endif %}
                    class="px-4 relative block w-full rounded-t-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                    placeholder="{{ field.label }}">
                {% elif field.name == "position" %}
                    <label class="block text-sm font-medium leading-6 text-gray-800 pb-2 pt-3">Position</label>
                    <select
                    name="{{ field.label }}"
                    {% if field.value %}value="{{ field.value }}"{% endif %}
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                    >
                      <option {% if not form.instance.pk %}selected{% endif %} >Choose position</option>
                        <option value="manager">Manager</option>
                        <option value="waiter">Waiter</option>
                        <option value="chef">Chef</option>
                        <option value="cleaner">Cleaner</option>
                        </select>
                {% elif field.name == "image" %}
                    <label class="block text-sm font-medium leading-6 text-gray-800 pb-2 pt-3">Upload your image</label>
                    <input type="{{ field.field.widget.input_type }}"
                    name="{{ field.label }}"
                    {% if field.value %}value="{{ field.value }}"{% endif %}
                    class="px-4 relative block w-full rounded-t-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                    placeholder="{{ field.label }}">
                {% elif field.name == "is_active" %}
                    <label class="block text-sm font-medium leading-6 text-gray-800 pb-2 pt-3">Employee is active</label>
                    <input  type="{{ field.field.widget.input_type }}"
                    name="{{ field.label }}"
                    {% if field.value %}value="{{ field.value }}"{% endif %}
                    checked
                    class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    placeholder="{{ field.label }}">
                {% endif %}
                    
            </div>
        {% endfor %} {% endcomment %}
                <div class="form-group">
                  <button type="submit" class="mt-3 inline-flex justify-center rounded-md bg-indigo-600 py-2 px-5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 w-full">{% if form.instance.pk %}Update{% else %}Add{% endif %}</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% comment %} <script>
    $(document).ready(function() {
      $("#emp-form input").classList.add("mt-2 px-3 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6");
    });
    $(document).ready(function() {
      $("#emp-form textarea").addClass("mt-2 px-3 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6");
    });
    document.getElementById("id_full_name").className += " mt-2 px-3 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6";
  </script> {% endcomment %}

<script>
document.getElementById("id_full_name").className += " mt-2 px-3 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6";
document.getElementById("id_address").className += " mt-2 px-3 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6";
document.getElementById("id_contact").className += " mt-2 px-3 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6";
document.getElementById("id_image").className += " mt-2 px-3 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6";
document.getElementById("id_is_active").className += "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600";
document.getElementById("id_salary").className += "mt-2 px-3 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6";
document.getElementById("id_position").className += "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500";
</script>

{% endblock %}

hr_management/templates/hr_management/employee_list.html
{% extends 'base.html' %}

{% block content %}
<div class="px-4 py-4 mx-4 my-4 rounded-3xl bg-gray-100 min-h-full">
    <a href="{% url 'employee_add' %}" class="flex-none rounded-md bg-indigo-500 py-2.5 px-3.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">Add Employee</a>
    <table class="min-w-full divide-y divide-gray-200 mt-5">
        <thead class="bg-gray-50">
          <tr>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">ID</th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Email</th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Position</th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Salary</th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for employee in employees %}
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">{{ employee.id }}</td>
              <td class="px-6 py-4 whitespace-nowrap">{{ employee.full_name }}</td>
              <td class="px-6 py-4 whitespace-nowrap">{{ employee.address }}</td>
              <td class="px-6 py-4 whitespace-nowrap">{{ employee.get_position_display }}</td>
              <td class="px-6 py-4 whitespace-nowrap">{{ employee.salary }}</td>
              <td class="px-6 py-4 whitespace-nowrap">
                <a href="{% url 'employee_edit' employee.id %}" class="btn btn-sm btn-primary text-indigo-600">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-5 w-5 inline-block mr-1">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                    </svg>
                </a>
                <a href="{% url 'employee_delete' employee.id %}" class="btn btn-sm btn-danger text-red-600">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-5 w-5 inline-block mr-1">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                    </svg>
                </a>
              </td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="6">No employees found.</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}